### ISSUE TITLE
how do you handle deleted documents?

### ISSUE THREAD

**Issue by jbotte** [eFishery/pouchy-store#4]
my concern is with pouch nothing is truly deleted so you could eventually run low on space?

**Comment by ans-4175** [comment]
Hey @jbotte thanks for your concerns.
Honestly we haven't had that issue yet for our use cases.
We don't use attachments and our data count still acceptable for browser.
But I think your concern is going to hit reality soon.

Based on my opinion I'd like to follow this
https://github.com/pouchdb/pouchdb/issues/4987#issuecomment-199700504
It seems we just need to tweak PouchDB config.

How do you think?
Whats your real case and how do you cope with that?

**Comment by jbotte** [comment]
That could possibly work, I’m currently considering a method in which on app startup I clone the existing database but filter out any docs that have been deleted still experimenting I’ll share my findings though
