### ISSUE TITLE
can you add join db for manipulation?

### ISSUE THREAD

**Issue by ajiagahari** [eFishery/pouchy-store#5]
actually we can manipulate the data by accessing `store.data`, but it would be convenience to 
add `join` method on store itself

**Comment by sumartoyo** [comment]
Join is practically impossible in document based DB such as PouchDB that we are using. It surely is possible to implement the method in application/library level and not in the database level, but it will be too complex to watch data change and notify change subscribers.

**Comment by ans-4175** [comment]
I think its a closed comment
